apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    #  github.com/project-slug: Arti1998/CICD-JavaWebApp
     github.com/project-slug:  ${{ steps['publish'].output.remoteUrl }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
 
  
