apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
#      github.com/project-slug:  ${{ steps['publish'].output.remoteUrl }}
     github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}} 
     backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: experimental
 
  
